export const START_FETCHING_TOP_CARD_DATA = "START_FETCHING_TOP_CARD_DATA"
export const SET_TOP_CARD_DATA = "SET_TOP_CARD_DATA";

export const START_FETCHING_ALL_COUNTRY_DATA = "START_FETCHING_ALL_COUNTRY_DATA";
export const SET_ALL_COUNTRY_DATA = "SET_ALL_COUNTRY_DATA";

export const START_FETCHING_WORLD_HIST_DATA = "START_FETCHING_WORLD_HIST_DATA";
export const SET_WORLD_HISTORICAL_DATA = "SET_WORLD_HISTORICAL_DATA";

export const START_FETCHING_COUNTRIES_HIST_DATA = "START_FETCHING_COUNTRIES_HIST_DATA";
export const SET_COUNTRIES_HISTORICAL_DATA = "SET_COUNTRIES_HISTORICAL_DATA";

export const START_FETCHING_NEWS_HEADLINES = "START_FETCHING_NEWS_HEADLINES";
export const SET_NEWS_HEADLINES = "SET_NEWS_HEADLINES";

export const SET_ERROR = "SET_ERROR";